(* IMPORT expression.ebnf *)
(* IMPORT token.ebnf *)

literal = boolean_literal;
negation = "!", boolean_expression;
parenthesized = "(", boolean_expression, ")";
boolean_operand =
    negation
    | parenthesized
    | literal;
binary_boolean_operation =
    boolean_operand, { ( "==" | "!=" | ">" | ">=" | "<" | "<=" | "&&" | "||" | "^" ), boolean_operand };
(* EXPORT *)
binary_expression = binary_boolean_operation;
