(* IMPORT numeric_expression.ebnf *)
(* IMPORT token.ebnf *)
(* IMPORT util.ebnf *)

(* EXPORT *)
expressions = [ expression, { ",",  expression } ];
(* EXPORT *)
expression =
    ambiguously_typed_expression
    | numeric_expression
    | boolean_expression
    | string_literal
    | invocation
    | identifier
    | chain;

(* TODO: put into own file *)
boolean_expression =
    boolean_expression, ( "||", "&&", "!" ), boolean_expression
    | "(", boolean_expression, ")"
    | boolean_literal
    | expression;

(* multiple constructs (e.g. functions or structs) can be invocated/initialized with the same syntax *)
invocation = identifier, "(", expressions, ")";
method_invocation = ".", invocation;
property_access = ".", identifier;
chain = expression, { ".", ( method_invocation, property_access ) };
