parameter = identifier, ":", identifier;
parameters = [ parameter, { ",", parameter } ];
type_parameters = "<", { identifier }, ">";
function_definition =
    "function", type_parameters, "(", parameters, ")", "{", statements, "}";
