(* IMPORT expression.ebnf *)
(* IMPORT token.ebnf *)
(* IMPORT util.ebnf *)

(* EXPORT *)
numeric_expression = sum;

sum = product { ( "+" | "-" ), product };
product = factor { ( "*" | "/" ), factor };
factor =
    unary
    | parenthesized
    | invocation
    | symbol
    | literal;
unary = ( "+" | "-" ), numeric_expression;
parenthesized = "(", numeric_expression, ")";
