(* it is assumed that any non-breaking whitespace and comments have been removed from the input *)

(* IMPORT expression.ebnf *)
(* IMPORT token.ebnf *)

variable_name = identifier, [ ":", identifier ];
assignment = variable_name, "=", expression;

condition = "if", "(", boolean_expression, ")", "{", statements, "}";
loop = "loop", "(", boolean_expression, ")", "{", statements, "}";

statement =
    assignment
    | condition
    | loop
    | expression;
statements = [ statement, { breaking_whitespace, statement } ];

(* EXPORT*)
(* ENTRY-POINT *)
start = statements;
