name: Deploy Module to GitHub Packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch dependencies
        run: npm install

      - name: Build module
        run: npm run build

      - name: Publish module
        run: |
          # clear .npmrc
          : > .npmrc
          # setup credentials
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" >> .npmrc
          # TODO: remove, just for testing purposes
          cat .npmrc
          # deploy module
          npm publish
