name: Deploy Module to GitHub Packages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:lts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch dependencies
        run: npm install

      - name: Build project
        run: npm run build
